// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScheduleService 是唯一暴露给前端的业务服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "./internal/domain/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BindApplication(app: application$0.App | null, window: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(561567315, app, window);
}

export function DeleteSchedule(id: string): $CancellablePromise<void> {
    return $Call.ByID(1253162582, id);
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(3048168000);
}

export function ListSchedules(): $CancellablePromise<domain$0.Schedule[] | null> {
    return $Call.ByID(411085518);
}

export function MinimiseWindow(): $CancellablePromise<void> {
    return $Call.ByID(1486230217);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2085519787);
}

export function RuntimeState(): $CancellablePromise<$models.RuntimeState> {
    return $Call.ByID(2893345157);
}

export function SaveSchedule(input: domain$0.ScheduleInput): $CancellablePromise<domain$0.Schedule> {
    return $Call.ByID(2467963464, input);
}

export function SendTestNotification(): $CancellablePromise<void> {
    return $Call.ByID(1573726209);
}

export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1507871585, enabled);
}

export function SetScheduleCompleted(id: string, completed: boolean): $CancellablePromise<domain$0.Schedule> {
    return $Call.ByID(1110065478, id, completed);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(854915373);
}

export function ToggleMaximiseWindow(): $CancellablePromise<void> {
    return $Call.ByID(4082609431);
}

export function WakeScheduler(): $CancellablePromise<void> {
    return $Call.ByID(2173995737);
}
