// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Schedule 是前端与 Go 服务之间共享的日程实体。
 */
export interface Schedule {
    "id": string;
    "title": string;
    "startAt": string;
    "endAt": string;
    "location"?: string;
    "notes"?: string;
    "color": string;
    "reminderOffsets": number[] | null;
    "status": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * ScheduleInput 表示新增或更新日程时允许前端提交的字段。
 */
export interface ScheduleInput {
    "id"?: string;
    "title": string;
    "startAt": string;
    "endAt": string;
    "location"?: string;
    "notes"?: string;
    "color": string;
    "reminderOffsets": number[] | null;
    "status"?: string;
}
